#
LOCAL_DIR := $(GET_LOCAL_DIR)

TARGET := yyd8163_tb_m

MODULES += app/mt_boot \
           dev/lcm

MTK_EMMC_SUPPORT = yes
DEFINES += MTK_NEW_COMBO_EMMC_SUPPORT
MTK_KERNEL_POWER_OFF_CHARGING = yes
DEFINES += SWCHR_POWER_PATH
DEFINES += MTK_BQ24261_SUPPORT
MTK_LCM_PHYSICAL_ROTATION = 90
#CUSTOM_LK_LCM="KR070IA4T_DSI_VDO jd9365_dsi_hd rm68200_dsi_cmd "
#CUSTOM_LK_LCM = rm68200_dsi_cmd
#CUSTOM_LK_LCM = rm68200_dsi_cmd nt51021
#nt35595_fhd_dsi_cmd_truly_nt50358 = yes

#FASTBOOT_USE_G_ORIGINAL_PROTOCOL = yes
MTK_SECURITY_SW_SUPPORT = yes
MTK_VERIFIED_BOOT_SUPPORT = yes
MTK_SEC_FASTBOOT_UNLOCK_SUPPORT = yes

#DEFINES += WITH_DEBUG_DCC=1
DEFINES += WITH_DEBUG_UART=1
#DEFINES += WITH_DEBUG_FBCON=1
#DEFINES += MACH_FPGA=y

